---
- name: Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ ecd_packages }}"
  loop_control:
    loop_var: pkg

- name: Install libisal
  package:
    name: libisal2
  when: ansible_architecture == 'x86_64'
...
