---
- name: Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ ecd_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags: install

- name: Install libisal
  package:
    name: libisal2
  when: ansible_architecture == 'x86_64'
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages_isal
  until: install_packages_isal is success
  retries: 5
  delay: 2
  tags: install
...
